### ISSUE TITLE
fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by lucacome** [docker/actions-toolkit#109]
When using `Git.context()` on a tag an error is returned:
```
fatal: ref HEAD is not a symbolic ref
```

This is because it runs
```
  public static async ref(): Promise<string> {
    return await Git.exec(['symbolic-ref', 'HEAD']);
  }
```
that is invalid on a tag.

This is causing https://github.com/docker/metadata-action/issues/293

**Comment by crazy-max** [comment]
Ah right in detached HEAD state we should fallback to `git describe`. Will fix this.
