### ISSUE TITLE
Optionally use disclosure elements to hide lengthy Docker build summary

### ISSUE THREAD

**Issue by ruffsl** [docker/actions-toolkit#369]
When using the `docker/bake-action@v6` action, the resulting build summary are rather long, taking up quite a bit of the vertical space from the rest of the user provide build summaries, requiring much more scroller for readers.

https://github.com/docker/actions-toolkit/blob/7b876a9e9528ce42864ddc1fef9499c2d498b2dc/src/github.ts#L205

While they are nicely detailed for debugging, would it be possible to allow the end user of the resulting docker actions to dynamically configure them to be encapsulate within a togglable disclosure element, via action input?

Even if the just the `<h2>Bake definition</h2>` and `<h2>Build inputs</h2>` sections had their body's nested under a collapsed disclosure element by default, that could be a big gain in reduction of line noise.

Related:
- https://github.com/orgs/community/discussions/44185#discussioncomment-9799051

**Comment by crazy-max** [comment]
Thanks for your feedback on this feature!

> When using the `docker/bake-action@v6` action

I think you mean `docker/bake-action@v5` :innocent:

> the resulting build summary are rather long, taking up quite a bit of the vertical space from the rest of the user provide build summaries, requiring much more scroller for readers.

Would you mind sharing the workflow run url of the repo affected by this? That would help to understand your issue. If you prefer to share materials (screenshot, video capture), feel free to do so.

> While they are nicely detailed for debugging, would it be possible to allow the end user of the resulting docker actions to dynamically configure them to be encapsulate within a togglable disclosure element, via action input?

I think we could make some enhancements and make `Build inputs` and `Bake definition` content togglable if it exceeds a predefined number of lines.

**Comment by colinhemmings** [comment]
Thanks for the feedback, @ruffsl; this is really useful. We will be investigating. Which pieces of information would be most valuable to us in these summaries?

**Comment by ruffsl** [comment]
> Would you mind sharing the workflow run url of the repo affected by this? That would help to understand your issue.

Sure, here is an anonymized example where it includes a trailing disclosure element to hind the lengthy docker build summary, so that PR reviewers can focus on finding the fully qualified tag names, while CI maintainers can expand the docker build summary for greater diagnostics and debugging.

---

## Base Images
| Image tag | Digest |
|-|-|
| `docker_action-tooler` | `sha256:49799b45cd4b8908fbe9867d0e9ac5df21785f02ec824cb2d4bbab15b4668765` |
| `docker_action-validator` | `sha256:d9be7802c1db8652efda7bfdc9aa1cf85a46adbe582712470c592c11e723aa68` |

### tooler
```
111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler@sha256:49799b45cd4b8908fbe9867d0e9ac5df21785f02ec824cb2d4bbab15b4668765
```

### validator
```
111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-validator@sha256:d9be7802c1db8652efda7bfdc9aa1cf85a46adbe582712470c592c11e723aa68
```

> example disclosure element that doesn't work in practice because of step isolation

<details><summary>Docker Build summary</summary>

<h1>Docker Build summary</h1>
<p>For a detailed look at the build, download the following build record archive and import it into Docker Desktop's Builds view. <br>
Build records include details such as timing, dependencies, results, logs, traces, and other information about a build. <a href="https://docs.docker.com/go/build-summary/">Learn more</a></p><p>:arrow_down: <a href="https://github.com/org/repo/actions/runs/123456789/artifacts/123456789"><strong>org~repo~ABJFAM+1.dockerbuild</strong></a> (106.48 KB)<br>
This file includes <strong>2 build records</strong>.</p><p>Find this useful? <a href="https://docs.docker.com/feedback/gha-build-summary">Let us know</a></p><h2>Preview</h2>
<table><tr><th>ID</th><th>Name</th><th>Status</th><th>Cached</th><th>Duration</th></tr><tr><td><code>ABJFAM</code></td><td><strong>repo (tooler)</strong></td><td>:white_check_mark: completed</td><td>66%</td><td>22s</td></tr><tr><td><code>NYMIYB</code></td><td><strong>repo (validator)</strong></td><td>:white_check_mark: completed</td><td>3%</td><td>24s</td></tr></table>
<h2>Build inputs</h2>
<pre lang="yaml"><code>files:
  - ./docker-bake.hcl
  - /home/runner/_work/_temp/docker-actions-toolkit-2FZiur/docker-metadata-action-bake.json
  - /home/runner/_work/_temp/docker-actions-toolkit-TzQCs8/docker-metadata-action-bake.json
targets:
  - tooler
  - validator
pull: true
provenance: 'false'
push: true
set:
  - '*.cache-from=type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:main-tooler.cache'
  - '*.cache-to=type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk,mode=max'
  - '*.cache-from=type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache'
  - tooler.cache-to=type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache,mode=max,image-manifest=true,oci-mediatypes=true
  - '*.cache-from=type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk'
</code></pre>
<h2>Bake definition</h2>
<pre lang="json"><code>{
  "group": {
    "default": {
      "targets": [
        "tooler",
        "validator"
      ]
    }
  },
  "target": {
    "tooler": {
      "attest": [
        "type=provenance,disabled=true"
      ],
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "DOCKER_META_IMAGES": "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo",
        "DOCKER_META_VERSION": "docker_action-tooler"
      },
      "labels": {
        "org.opencontainers.image.created": "2024-06-17T18:54:18.131Z",
        "org.opencontainers.image.description": "Experimentation repo for refactoring auto integration repo",
        "org.opencontainers.image.licenses": "",
        "org.opencontainers.image.revision": "50e0ecd7bf698a01710d08ce052319b8d46b50fd",
        "org.opencontainers.image.source": "https://github.com/org/repo",
        "org.opencontainers.image.title": "repo",
        "org.opencontainers.image.url": "https://github.com/org/repo",
        "org.opencontainers.image.version": "docker_action-tooler"
      },
      "tags": [
        "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler"
      ],
      "cache-from": [
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:main-tooler.cache",
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache",
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk"
      ],
      "cache-to": [
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk,mode=max",
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache,mode=max,image-manifest=true,oci-mediatypes=true"
      ],
      "target": "tooler",
      "output": [
        "type=image,push=true,push=true,push=true,push=true,push=true"
      ],
      "pull": true,
      "no-cache": false
    },
    "validator": {
      "attest": [
        "type=provenance,disabled=true"
      ],
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "DOCKER_META_IMAGES": "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo",
        "DOCKER_META_VERSION": "docker_action-validator"
      },
      "labels": {
        "org.opencontainers.image.created": "2024-06-17T18:54:17.585Z",
        "org.opencontainers.image.description": "Experimentation repo for refactoring auto integration repo",
        "org.opencontainers.image.licenses": "",
        "org.opencontainers.image.revision": "50e0ecd7bf698a01710d08ce052319b8d46b50fd",
        "org.opencontainers.image.source": "https://github.com/org/repo",
        "org.opencontainers.image.title": "repo",
        "org.opencontainers.image.url": "https://github.com/org/repo",
        "org.opencontainers.image.version": "docker_action-validator"
      },
      "tags": [
        "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-validator"
      ],
      "cache-from": [
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:main-tooler.cache",
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache",
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk"
      ],
      "cache-to": [
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk,mode=max"
      ],
      "target": "validator",
      "output": [
        "type=image,push=true,push=true,push=true,push=true"
      ],
      "pull": true,
      "no-cache": false
    }
  }
}</code></pre>
<hr>

**Comment by ruffsl** [comment]
> content togglable if it exceeds a predefined number of lines.

I would prefer tighter control over the rendering, rather than hard coded hursitics.

Perhaps a verbosity parameter could be used to fold headings of different levels? E.g:

```yaml
with:
  verbosity: 0
```

would enclose all headings greater than the `<h0>` tag, E.g everything.

```yaml
with:
  verbosity: 1
```

while would similarly enclose all headings greater than the `<h1>` tag. E.g:

---

## Base Images
| Image tag | Digest |
|-|-|
| `docker_action-tooler` | `sha256:49799b45cd4b8908fbe9867d0e9ac5df21785f02ec824cb2d4bbab15b4668765` |
| `docker_action-validator` | `sha256:d9be7802c1db8652efda7bfdc9aa1cf85a46adbe582712470c592c11e723aa68` |

### tooler
```
111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler@sha256:49799b45cd4b8908fbe9867d0e9ac5df21785f02ec824cb2d4bbab15b4668765
```

### validator
```
111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-validator@sha256:d9be7802c1db8652efda7bfdc9aa1cf85a46adbe582712470c592c11e723aa68
```

<h1>Docker Build summary</h1>
<p>For a detailed look at the build, download the following build record archive and import it into Docker Desktop's Builds view. <br>
Build records include details such as timing, dependencies, results, logs, traces, and other information about a build. <a href="https://docs.docker.com/go/build-summary/">Learn more</a></p><p>:arrow_down: <a href="https://github.com/org/repo/actions/runs/123456789/artifacts/123456789"><strong>org~repo~ABJFAM+1.dockerbuild</strong></a> (106.48 KB)<br>
This file includes <strong>2 build records</strong>.</p><p>Find this useful? <a href="https://docs.docker.com/feedback/gha-build-summary">Let us know</a></p><h2>Preview</h2>
<table><tr><th>ID</th><th>Name</th><th>Status</th><th>Cached</th><th>Duration</th></tr><tr><td><code>ABJFAM</code></td><td><strong>repo (tooler)</strong></td><td>:white_check_mark: completed</td><td>66%</td><td>22s</td></tr><tr><td><code>NYMIYB</code></td><td><strong>repo (validator)</strong></td><td>:white_check_mark: completed</td><td>3%</td><td>24s</td></tr></table>

<details><summary>Build inputs</summary>

<h2>Build inputs</h2>
<pre lang="yaml"><code>files:
  - ./docker-bake.hcl
  - /home/runner/_work/_temp/docker-actions-toolkit-2FZiur/docker-metadata-action-bake.json
  - /home/runner/_work/_temp/docker-actions-toolkit-TzQCs8/docker-metadata-action-bake.json
targets:
  - tooler
  - validator
pull: true
provenance: 'false'
push: true
set:
  - '*.cache-from=type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:main-tooler.cache'
  - '*.cache-to=type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk,mode=max'
  - '*.cache-from=type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache'
  - tooler.cache-to=type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache,mode=max,image-manifest=true,oci-mediatypes=true
  - '*.cache-from=type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk'
</code></pre>

</details>

<details><summary>Bake definition</summary>

<h2>Bake definition</h2>
<pre lang="json"><code>{
  "group": {
    "default": {
      "targets": [
        "tooler",
        "validator"
      ]
    }
  },
  "target": {
    "tooler": {
      "attest": [
        "type=provenance,disabled=true"
      ],
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "DOCKER_META_IMAGES": "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo",
        "DOCKER_META_VERSION": "docker_action-tooler"
      },
      "labels": {
        "org.opencontainers.image.created": "2024-06-17T18:54:18.131Z",
        "org.opencontainers.image.description": "Experimentation repo for refactoring auto integration repo",
        "org.opencontainers.image.licenses": "",
        "org.opencontainers.image.revision": "50e0ecd7bf698a01710d08ce052319b8d46b50fd",
        "org.opencontainers.image.source": "https://github.com/org/repo",
        "org.opencontainers.image.title": "repo",
        "org.opencontainers.image.url": "https://github.com/org/repo",
        "org.opencontainers.image.version": "docker_action-tooler"
      },
      "tags": [
        "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler"
      ],
      "cache-from": [
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:main-tooler.cache",
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache",
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk"
      ],
      "cache-to": [
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk,mode=max",
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache,mode=max,image-manifest=true,oci-mediatypes=true"
      ],
      "target": "tooler",
      "output": [
        "type=image,push=true,push=true,push=true,push=true,push=true"
      ],
      "pull": true,
      "no-cache": false
    },
    "validator": {
      "attest": [
        "type=provenance,disabled=true"
      ],
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "DOCKER_META_IMAGES": "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo",
        "DOCKER_META_VERSION": "docker_action-validator"
      },
      "labels": {
        "org.opencontainers.image.created": "2024-06-17T18:54:17.585Z",
        "org.opencontainers.image.description": "Experimentation repo for refactoring auto integration repo",
        "org.opencontainers.image.licenses": "",
        "org.opencontainers.image.revision": "50e0ecd7bf698a01710d08ce052319b8d46b50fd",
        "org.opencontainers.image.source": "https://github.com/org/repo",
        "org.opencontainers.image.title": "repo",
        "org.opencontainers.image.url": "https://github.com/org/repo",
        "org.opencontainers.image.version": "docker_action-validator"
      },
      "tags": [
        "111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-validator"
      ],
      "cache-from": [
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:main-tooler.cache",
        "type=registry,ref=111111111111.dkr.ecr.us-east-1.amazonaws.com/repo:docker_action-tooler.cache",
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk"
      ],
      "cache-to": [
        "type=s3,blobs_prefix=cache/repo/,manifests_prefix=cache/repo/,region=us-east-1,bucket=abcdefghijk,mode=max"
      ],
      "target": "validator",
      "output": [
        "type=image,push=true,push=true,push=true,push=true"
      ],
      "pull": true,
      "no-cache": false
    }
  }
}</code></pre>
<hr>

</details>

**Comment by ruffsl** [comment]
> Which pieces of information would be most valuable to use in these summaries?

Well, it would be kind of nice for the build summary to include copyable URIs to the fully qualified tag names.

For example, this is what I've been doing to easily surface the tag names to our end users:

```yaml
    - name: Job Workflow Info
      id: job_workflow_info
      shell: bash
      run: |
        debugger_image_name="${{ fromJSON(steps.bake_prod_stages.outputs.metadata)['debugger']['image.name'] }}"
        debugger_image_digest="${{ fromJSON(steps.bake_prod_stages.outputs.metadata)['debugger']['containerimage.digest'] }}"
        debugger_image="${debugger_image_name}@${debugger_image_digest}"
        echo "debugger_image=${debugger_image}" >> $GITHUB_OUTPUT

        releaser_image_name="${{ fromJSON(steps.bake_prod_stages.outputs.metadata)['releaser']['image.name'] }}"
        releaser_image_digest="${{ fromJSON(steps.bake_prod_stages.outputs.metadata)['releaser']['containerimage.digest'] }}"
        releaser_image="${releaser_image_name}@${releaser_image_digest}"
        echo "releaser_image=${releaser_image}" >> $GITHUB_OUTPUT

        cat << EOF > $GITHUB_STEP_SUMMARY
        ## Prod Images
        | Image tag | Digest |
        |-|-|
        | \`${debugger_image_name##*:}\` | \`${debugger_image_digest}\` |
        | \`${releaser_image_name##*:}\` | \`${releaser_image_digest}\` |

        ### debugger
        \`\`\`
        ${debugger_image}
        \`\`\`

        ### releaser
        \`\`\`
        ${releaser_image}
        \`\`\`
        EOF
```

**Comment by Pesa** [comment]
I have similar feedback on the new build summary feature: it is quite verbose in general. I actually like the "Preview" section/table(*) a lot, but the "Build inputs" section doesn't seem very useful unless someone is debugging the workflow (and in that case I would look at the full logs anyway).

See [here](https://github.com/named-data/ndn-cxx/actions/runs/9556851874) for an example of a workflow run.

I'd like to request an option to hide the "Build inputs" section in a `<details>` element, or even suppress it altogether. In fact, I'd argue hiding the section should be the default behavior. I'm using a similar technique with `<details>` for the job summary generated by our [reusable workflow](https://github.com/named-data/actions/blob/2f2ef31dba962c4761c6a47a6bbecbbcde376903/.github/workflows/docker-image.yml#L214).

(*) while at it, I suggest adding another column with the image size :)

**Comment by crazy-max** [comment]
@ruffsl @Pesa Thanks for your feedback, I will make some changes and keep you posted.
