### ISSUE TITLE
Ollama running with Github actions using dockerfile

### ISSUE THREAD

**Issue by andreea-ghe** [docker/actions-toolkit#424]
Does anyone know how can one configure a Github Actions yml file to serve ollama and to load it with a base model (like llama3)?

This is the dockerfile i used:
FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN curl -fsSL https://ollama.com/install.sh | sh

RUN nohup ollama serve > ollama.log 2>&1 & sleep 10 && ollama pull llama3

EXPOSE 11434

CMD nohup ollama serve > ollama.log 2>&1 & tail -f /dev/null

I tried to use it like this in the workflow:
name: Ollama
 
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
 
jobs:
  auxiliary:
    runs-on: ubuntu-latest
    container:
      image: username/ollama_container:latest
      ports:
        - 11434:11434
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /__w/ai-integration/ai-integration

      - name: Start Ollama Service
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 5
          curl -i http://localhost:11434 || (cat ollama.log && exit 1)
          tail -f /dev/null &

but if i don't pull the llama3 model inside the workflow, it won't be found, returning this error:
{"error":"model \"llama3\" not found, try pulling it first"}
Thank you!

**Comment by crazy-max** [comment]
Hi, this repository is about our internal toolkit to develop GitHub Actions. For help about using GitHub Actions I suggest to open a thread at https://github.com/orgs/community/discussions/categories/actions.
